// <auto-generated />
using System;
using Hospital_app_02_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hospital_app_02_BE.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20201229200658_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Everst, 8577",
                            Email = "john@hospital.com",
                            EmploymentDate = "12/29/2020 10:06:57 PM",
                            Name = "John",
                            Password = "secret11S",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            Role = "Šeimos gydytojas",
                            Surname = "Root",
                            Token = "testTokenHAHAHAHAAHAHAH"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Everst, 8577",
                            Email = "stefan@hospital.com",
                            EmploymentDate = "12/29/2020 10:06:57 PM",
                            Name = "Stefan",
                            Password = "secret11S",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            Role = "Šeimos gydytojas",
                            Surname = "Green",
                            Token = "testTokenHAHAHAHAAHAHAH"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Everst, 8577",
                            Email = "john@hospital.com",
                            EmploymentDate = "12/29/2020 10:06:57 PM",
                            Name = "Greg",
                            Password = "secret11S",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            Role = "Chirurgas",
                            Surname = "Root",
                            Token = "testTokenHAHAHAHAAHAHAH"
                        });
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Evergreeen 18, 8577",
                            Email = "linanana@gmail.com",
                            Name = "Lina",
                            Password = "linaSlapta123",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            RiskLevel = 5,
                            Surname = "Dragel",
                            Token = "testToken44775484"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Evergreeen 18, 8577",
                            Email = "jonis@gmail.com",
                            Name = "Jons",
                            Password = "jonisNesakysiu123",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            RiskLevel = 1,
                            Surname = "Petrauskas",
                            Token = "testToken44775485"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Evergreeen 18, 8577",
                            Email = "antanuks@gmail.com",
                            Name = "Antanas",
                            Password = "linosSlaptas123",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            RiskLevel = 5,
                            Surname = "Dragel",
                            Token = "testToken44775486"
                        });
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2020, 12, 29, 22, 6, 57, 817, DateTimeKind.Local).AddTicks(3469),
                            Description = "Karščiavimas",
                            EmployeeId = 1,
                            PatientId = 1,
                            Title = "Registracija pas šeimos daktarą"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2020, 12, 29, 22, 6, 57, 817, DateTimeKind.Local).AddTicks(6015),
                            Description = "Pilvo skausmai",
                            EmployeeId = 1,
                            PatientId = 2,
                            Title = "Registracija pas šeimos daktarą"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2020, 12, 29, 22, 6, 57, 817, DateTimeKind.Local).AddTicks(6109),
                            Description = "Kojos operacija",
                            EmployeeId = 3,
                            PatientId = 1,
                            Title = "Registracija pas chirurgą"
                        });
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Registration", b =>
                {
                    b.HasOne("Hospital_app_02_BE.Data.Entities.Employee", "Employee")
                        .WithMany("Registrations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_app_02_BE.Data.Entities.Patient", "Patient")
                        .WithMany("Registrations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Employee", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Patient", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
