// <auto-generated />
using System;
using Hospital_app_02_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hospital_app_02_BE.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20210501211433_Registrations_addedDoctorCommentColumn")]
    partial class Registrations_addedDoctorCommentColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Critical_situation_confirmations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Critical_Situation_Confirmations");
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmploymentDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Everst, 8577",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@hospital.com",
                            EmploymentDate = "5/2/2021 12:14:32 AM",
                            Name = "John",
                            Password = "secret11S",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            Role = "Šeimos gydytojas",
                            Surname = "Root",
                            Token = "testTokenHAHAHAHAAHAHAH"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Everst, 8577",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "stefan@hospital.com",
                            EmploymentDate = "5/2/2021 12:14:32 AM",
                            Name = "Stefan",
                            Password = "secret11S",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            Role = "Šeimos gydytojas",
                            Surname = "Green",
                            Token = "testTokenHAHAHAHAAHAHAH"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Everst, 8577",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john@hospital.com",
                            EmploymentDate = "5/2/2021 12:14:32 AM",
                            Name = "Greg",
                            Password = "secret11S",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            Role = "Chirurgas",
                            Surname = "Root",
                            Token = "testTokenHAHAHAHAAHAHAH"
                        });
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 5, 2, 0, 14, 32, 714, DateTimeKind.Local).AddTicks(4372),
                            Description = "Greitu metu pasirodys naujos vakcinos nuo COVID-19",
                            Title = "Naujos vakcinos importas"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 5, 2, 0, 14, 32, 714, DateTimeKind.Local).AddTicks(4756),
                            Description = "Šiuo metu vyksta laikini sistemos atnaujinimai, todėl sistema gali veikti netinkamai. Atsiprašome.",
                            Title = "Sistemos atnaujinimai"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 5, 2, 0, 14, 32, 714, DateTimeKind.Local).AddTicks(4776),
                            Description = "Šiuo metu gydymo įstaiga įdarbina gausybę naujų žmonių!",
                            Title = "Naujas kolektyvas"
                        });
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Evergreeen 18, 8577",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "linanana@gmail.com",
                            Name = "Lina",
                            Password = "linaSlapta123",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            RiskLevel = 5,
                            Surname = "Dragel",
                            Token = "testToken44775484"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Evergreeen 18, 8577",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jonis@gmail.com",
                            Name = "Jons",
                            Password = "jonisNesakysiu123",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            RiskLevel = 1,
                            Surname = "Petrauskas",
                            Token = "testToken44775485"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Evergreeen 18, 8577",
                            BirthDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "antanuks@gmail.com",
                            Name = "Antanas",
                            Password = "linosSlaptas123",
                            PersonalCode = "388888888",
                            Phone = "867784585",
                            RiskLevel = 5,
                            Surname = "Dragel",
                            Token = "testToken44775486"
                        });
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PatientId");

                    b.ToTable("Registrations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2021, 5, 2, 0, 14, 32, 714, DateTimeKind.Local).AddTicks(2676),
                            Description = "Karščiavimas",
                            EmployeeId = 1,
                            PatientId = 1,
                            Title = "Registracija pas šeimos daktarą"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2021, 5, 2, 0, 14, 32, 714, DateTimeKind.Local).AddTicks(3482),
                            Description = "Pilvo skausmai",
                            EmployeeId = 1,
                            PatientId = 2,
                            Title = "Registracija pas šeimos daktarą"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2021, 5, 2, 0, 14, 32, 714, DateTimeKind.Local).AddTicks(3516),
                            Description = "Kojos operacija",
                            EmployeeId = 3,
                            PatientId = 1,
                            Title = "Registracija pas chirurgą"
                        });
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Critical_situation_confirmations", b =>
                {
                    b.HasOne("Hospital_app_02_BE.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Registration", b =>
                {
                    b.HasOne("Hospital_app_02_BE.Data.Entities.Employee", "Employee")
                        .WithMany("Registrations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_app_02_BE.Data.Entities.Patient", "Patient")
                        .WithMany("Registrations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Employee", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("Hospital_app_02_BE.Data.Entities.Patient", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
